all:

  children:

    linux:
      hosts:

        exodus-platform-01:
        exodus-services-01:

        exodus-observability-01:
        exodus-grafana-01:
        exodus-ingress-01:
        exodus-logging-01:
        exodus-automation-01:

    windows:
      hosts:

        exodus-ad-01:

    platform:
      hosts:

        exodus-platform-01:
        exodus-services-01:

    monitoring:
      hosts:

        exodus-observability-01:
        exodus-grafana-01:

    ingress:
      hosts:

        exodus-ingress-01:

    logging:
      hosts:

        exodus-logging-01:

    automation:
      hosts:

        exodus-automation-01:

    identity:
      hosts:

        exodus-ad-01:
